name: ${project.name}
main: ${project.groupId}.${upload.dbo.slug}.${project.name}
version: ${project.version}
description: ${project.description}
author: chaseoes
commands:
  ${upload.dbo.slug}:
    description: The central command for the ${project.name} plugin.
    usage: /<command> [args]
